In [7]:
# Vamos a obtener los datos de entrada de Centauro usando la clase Drillhole del módulo Drillhole.py

# Dado las tablas ASSAY.csv, COLLAR.csv, SURVEY.csv como entrada
# Obtenemos => desurveyed_assay.csv que contendrá las coordenadas (Xm, Ym, Zm) y ángulos AZM, DIP junto a su ley de oro (Au) y cobre (Cu)

import pandas as pd
import numpy as np
from Drillhole import Drillhole

In [10]:
collar = pd.read_csv('../DEEPSKILL_DATA/COLLAR.csv')
survey = pd.read_csv('../DEEPSKILL_DATA/SURVEY.csv')
assay = pd.read_csv('../DEEPSKILL_DATA/ASSAY.csv')

In [3]:
print(collar.dtypes)

BHID         object
XCOLLAR     float64
YCOLLAR     float64
ZCOLLAR     float64
ENDDEPTH    float64
dtype: object

In [4]:
print(survey.dtypes)

BHID     object
AT      float64
AZ      float64
DIP     float64
dtype: object

In [5]:
assay = assay.replace('-', 0.)

assay['Au_ppm'] = assay['Au_ppm'].astype(float)
assay['Ag_ppm'] = assay['Ag_ppm'].astype(float)
assay['Cu_%'] = assay['Cu_%'].astype(float)
assay['Zn_ppm'] = assay['Zn_ppm'].astype(float)
assay['Mo_ppm'] = assay['Mo_ppm'].astype(float)
assay['As_ppm'] = assay['As_ppm'].astype(float)
assay['Sb_ppm'] = assay['Sb_ppm'].astype(float)
assay['Pb_ppm'] = assay['Pb_ppm'].astype(float)

assay.drop(columns=['Ag_ppm', 'Zn_ppm', 'Mo_ppm', 'As_ppm', 'Sb_ppm', 'Pb_ppm'], inplace=True)

print(assay.dtypes)

BHID         object
FROM        float64
TO          float64
N_SAMPLE     object
Au_ppm      float64
Cu_%        float64
dtype: object

In [6]:
assay.head(10)

      BHID   FROM     TO    N_SAMPLE  Au_ppm   Cu_%
0  PAM-001   0.00   1.95  PPA-000001   0.040  0.008
1  PAM-001   1.95   3.55  PPA-000002   0.078  0.004
2  PAM-001   3.55   5.55  PPA-000003   0.039  0.009
3  PAM-001   5.55   7.55  PPA-000004   0.043  0.008
4  PAM-001   7.55   9.55  PPA-000005   0.073  0.002
5  PAM-001   9.55  11.55  PPA-000006   0.033  0.004
6  PAM-001  11.55  13.55  PPA-000007   0.047  0.007
7  PAM-001  13.55  15.55  PPA-000008   0.035  0.006
8  PAM-001  15.55  17.55  PPA-000009   0.032  0.008
9  PAM-001  17.55  19.32  PPA-000010   0.039  0.010

In [7]:
mydholedb = Drillhole(collar, survey)
mydholedb.add_table(assay, 'assay')

mydholedb.desurvey_table('assay')

In [8]:
mydholedb.table['assay'].head(10)

,BHID,FROM,TO,N_SAMPLE,Au_ppm,Cu_%,xb,yb,zb,xe,...,ze,xm,ym,zm,azmb,dipb,azme,dipe,azmm,dipm
0,PAM-001,0.00,1.95,PPA-000001,0.040,0.008,347099.770000,8.820069e+06,4328.059000,347100.719394,...,4326.377460,347100.244697,8.820069e+06,4327.218230,74.055,59.579,74.055,59.579,74.055,59.579
1,PAM-001,1.95,3.55,PPA-000002,0.078,0.004,347100.719394,8.820069e+06,4326.377460,347101.498383,...,4324.997735,347101.108888,8.820069e+06,4325.687598,74.055,59.579,74.055,59.579,74.055,59.579
2,PAM-001,3.55,5.55,PPA-000003,0.039,0.009,347101.498383,8.820069e+06,4324.997735,347102.472120,...,4323.273079,347101.985252,8.820069e+06,4324.135407,74.055,59.579,74.055,59.579,74.055,59.579
3,PAM-001,5.55,7.55,PPA-000004,0.043,0.008,347102.472120,8.820069e+06,4323.273079,347103.445857,...,4321.548423,347102.958989,8.820070e+06,4322.410751,74.055,59.579,74.055,59.579,74.055,59.579
4,PAM-001,7.55,9.55,PPA-000005,0.073,0.002,347103.445857,8.820070e+06,4321.548423,347104.419594,...,4319.823766,347103.932725,8.820070e+06,4320.686094,74.055,59.579,74.055,59.579,74.055,59.579
5,PAM-001,9.55,11.55,PPA-000006,0.033,0.004,347104.419594,8.820070e+06,4319.823766,347105.393331,...,4318.099110,347104.906462,8.820070e+06,4318.961438,74.055,59.579,74.055,59.579,74.055,59.579
6,PAM-001,11.55,13.55,PPA-000007,0.047,0.007,347105.393331,8.820070e+06,4318.099110,347106.367068,...,4316.374454,347105.880199,8.820070e+06,4317.236782,74.055,59.579,74.055,59.579,74.055,59.579
7,PAM-001,13.55,15.55,PPA-000008,0.035,0.006,347106.367068,8.820071e+06,4316.374454,347107.340805,...,4314.649797,347106.853936,8.820071e+06,4315.512126,74.055,59.579,74.055,59.579,74.055,59.579
8,PAM-001,15.55,17.55,PPA-000009,0.032,0.008,347107.340805,8.820071e+06,4314.649797,347108.314542,...,4312.925141,347107.827673,8.820071e+06,4313.787469,74.055,59.579,74.055,59.579,74.055,59.579
9,PAM-001,17.55,19.32,PPA-000010,0.039,0.010,347108.314542,8.820071e+06,4312.925141,347109.176299,...,4311.398820,347108.745420,8.820071e+06,4312.161981,74.055,59.579,74.055,59.579,74.055,59.579

In [10]:
mydholedb.table['assay'].to_csv('../CENTAURO_DATA/desurveyed_assay.csv', index=False)

In [11]:
centauro_df = pd.read_csv('../DEEPSKILL_DATA/desurveyed_assay.csv')

centauro_df.rename(columns={'xm' : 'X', 'ym' : 'Y', 'zm' : 'Z', 'azmm' : 'AZM', 'dipm' : 'DIP'}, inplace=True)
predictors = ['X', 'Y', 'Z', 'AZM', 'DIP', 'Au_ppm']
centauro_df[predictors] = centauro_df[predictors].round(3)

predictors = ['BHID', 'FROM', 'TO'] + predictors

centauro_df.loc[0, 'X'] = 512100.245
centauro_df.loc[1, 'X'] = 512101.109
centauro_df.loc[2, 'X'] = 512101.985

centauro_df.loc[0, 'Y'] = 623100.786
centauro_df.loc[1, 'Y'] = 623101.033
centauro_df.loc[2, 'Y'] = 623101.283

centauro_df.loc[0, 'Z'] = 3710.218
centauro_df.loc[1, 'Z'] = 3710.688
centauro_df.loc[2, 'Z'] = 3710.135

centauro_df[predictors].head(3)

,BHID,FROM,TO,X,Y,Z,AZM,DIP,Au_ppm
0,PAM-001,0.00,1.95,512100.245,623100.786,3710.218,74.055,59.579,0.040
1,PAM-001,1.95,3.55,512101.109,623101.033,3710.688,74.055,59.579,0.078
2,PAM-001,3.55,5.55,512101.985,623101.283,3710.135,74.055,59.579,0.039